### ISSUE TITLE
worldwide image to tiles return a error

### ISSUE THREAD

**Issue by zhongshuiyuan** [Gigas002/GTiff2Tiles#111]
**Describe the bug**
A clear and concise description of what the bug is; `Exception` text (if there was).

**To Reproduce**
Describe steps to reproduce the behavior.

If you’re running in IDE, please also specify **exact file** and **string number** in it, that throws an `Exception`.

**Input data info**
Some info about your input **GeoTIFF**, causing error, at least projection. Would be better, if you can send **gdalinfo** screenshot.
Ideally – upload **GeoTIFF**, that causes the error (you can use e.g. Google Drive to share it, since GitHub has some restrictions to the attachment’s size).

**Expected behavior**

**Desktop:**

- OS: [e.g. Windows 10 x64]
- Version [e.g. 1.2.0.]. Please, also specify here, if you’re building from the source and not using the pre-compiled binaries on [releases](https://github.com/Gigas002/GTiff2Tiles/releases) page.

**Additional context**

I am try map tiler  worldwide image,it is return a error:System.OverflowException:“Arithmetic operation resulted in an overflow.”
the Number big the Int32 max value.

![QQ截图20210121150420](https://user-images.githubusercontent.com/8955999/105315241-fd532100-5bf9-11eb-9560-943d3962c2f6.png)

**Comment by Gigas002** [comment]
Hello, @zhongshuiyuan.
Thank you for reporting this! Starting from 15 zoom, there's too many tiles to create, so it's count oveflows the `Int32` type. I think of two possible options on this:

1. Use `Int64` (max value `9,223,372,036,854,775,807`) or `UInt64` (`18,446,744,073,709,551,615`). But reporting progress on such a large output would cost A LOT of performance because of millions and millions of system calls to report the progress to console, so there's other option;
2. Don't report progress if tiles count was too much (but tell the user about that decision).

**Comment by Gigas002** [comment]
In the end I've decided that this problem shouldn't be fixed honestly. I thinks it is possible, that creating even `2,147,483,647` (max `Int32` value in c#) can break/lead to big problems with lifetime and performance of your HDD, so it's better to throw an exception.
